### ISSUE TITLE
Non riesco a trovare il Makefile

### ISSUE THREAD

**Issue by defra91** [gfornari/qChart#1]
Ricordo che Ranzato ci chiese esplicitamente di produrre un Makefile, ma non riesco a trovarlo nel progetto.

**Comment by gfornari** [comment]
Although most of the documentation is in Italian, it tries to be an English repo, so I answer in English :)

I think you should generate a Makefile running `qmake qChart.pro` from the root, then you should be able to run `make`. Of course, you must have Qt installed first.

I'll update the README with these info.
